name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Print new build number
      run: echo ${{ github.run_number }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sachinpal064/grafana:v1
